import os
import base64
import requests
from unstructured.partition.pdf import partition_pdf
from app.config import RAW_IMAGE_DIR, OLLAMA_BASE_URL, VISION_LLM_MODEL_NAME

def encode_image_to_base64(image_path):
    """Encodes an image to a base64 string to send to LLaVA."""
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

def summarize_architecture_diagram(image_path):
    """Sends the extracted diagram to local LLaVA for technical summarization."""
    print(f"[*] Sending {image_path} to LLaVA for summarization...")
    
    base64_image = encode_image_to_base64(image_path)
    
    prompt = (
        "You are an expert computer vision researcher. Analyze this architecture diagram. "
        "Describe the layers, connections, and mathematical operations shown. "
        "Do not use filler words. Be highly technical."
    )

    payload = {
        "model": VISION_LLM_MODEL_NAME,
        "prompt": prompt,
        "images": [base64_image],
        "stream": False
    }

    try:
        response = requests.post(f"{OLLAMA_BASE_URL}/api/generate", json=payload)
        response.raise_for_status()
        return response.json().get("response", "Failed to generate summary.")
    except Exception as e:
        print(f"[!] Error calling Ollama: {e}")
        return "Image summarization failed."

def process_research_paper(pdf_path):
    """
    Parses a CV research paper, separating text and images, 
    and generates summaries for the architectural diagrams.
    """
    print(f"[*] Partitioning PDF: {pdf_path}")
    
    elements = partition_pdf(
        filename=pdf_path,
        strategy="hi_res",
        extract_images_in_pdf=True,
        extract_image_block_output_dir=RAW_IMAGE_DIR,
    )

    processed_chunks = []

    for element in elements:
        if element.category == "Image":
            # Extract the actual file path generated by the library from the metadata
            image_path = getattr(element.metadata, "image_path", None)
            
            if image_path and os.path.exists(image_path):
                summary = summarize_architecture_diagram(image_path)
                
                processed_chunks.append({
                    "type": "image_summary",
                    "content": summary,
                    "metadata": {"source_image": image_path}
                })
            else:
                print(f"[!] Warning: Image detected but path could not be resolved for element {element.id}")
        
        elif element.category in ["NarrativeText", "Title", "Text"]:
            processed_chunks.append({
                "type": "text",
                "content": str(element),
                "metadata": {"source_page": element.metadata.page_number}
            })

    print(f"[*] Processing complete. Total chunks extracted: {len(processed_chunks)}")
    return processed_chunks